spring.application.name=devshowcase
# Nome da aplicação
spring.application.name=devshowcase-api

# Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:devshowcase

# Driver do banco
spring.datasource.driver-class-name=org.h2.Driver

# Usuário do banco
spring.datasource.username=sa

# Senha (vazia)
spring.datasource.password=

# Configuração do JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Criar e atualizar tabelas automaticamente
spring.jpa.hibernate.ddl-auto=create-drop

# Mostrar comandos SQL no terminal
spring.jpa.show-sql=true

# Formatar o SQL
spring.jpa.properties.hibernate.format_sql=true

# Habilitar console do H2
spring.h2.console.enabled=true

# Caminho do console
spring.h2.console.path=/h2-console

#Implementação da documentação interativa da API acessível via Swagger
springdoc.swagger-ui.path=/swagger-ui.html